name = "daimon-network-api"
main = "src/index.ts"
compatibility_date = "2024-02-01"

[vars]
REGISTRY_ADDRESS = "0x3081aE79B403587959748591bBe1a2c12AeF5167"
DAIMON_TOKEN = "0x98c51C8E958ccCD37F798b2B9332d148E2c05D57"

[[kv_namespaces]]
binding = "CACHE"
id = "placeholder"
